### ISSUE TITLE
Incompatibility with InfluxDB extension

### ISSUE THREAD

**Issue by peteh** [Makhuta/homeassistant-duolingo#4]
For some reason this extension throws exceptions when using Homeassistant's InfluxDB extension 

```
2024-12-03 13:27:09.718 ERROR (influxdb) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 599, in run
    self.write_to_influxdb(json)
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 575, in write_to_influxdb
    self.influx.write(json)
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 365, in write_v2
    write_api.write(**data)
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write_api.py", line 363, in write
    self._serialize(record, write_precision, payloads, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write_api.py", line 440, in _serialize
    self._serialize(item, write_precision, payload, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write_api.py", line 428, in _serialize
    self._serialize(Point.from_dict(record, write_precision=write_precision, **kwargs),
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write_api.py", line 425, in _serialize
    self._serialize(record.to_line_protocol(), record.write_precision, payload, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 233, in to_line_protocol
    _fields = _append_fields(self._fields, self._field_types)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 312, in _append_fields
    raise ex
  File "/usr/local/lib/python3.12/site-packages/influxdb_client/client/write/point.py", line 285, in _append_fields
    for field, value in sorted(fields.items()):
                        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

```

I tried to debug a bit further what could cause the sorted function to fail here but I'm kinda at my end. It fails when the duo lingo items are updated, this is the data point that is supposed to be added in the form of key -> value printed into a string: 

```
2024-12-03 13:31:45.465 ERROR (influxdb) [homeassistant.components.influxdb] ("value -> 1.0
1_str -> {'display_name': 'Pete', 'has_plus': False, 'has_recent_activity_15': True, 'score': 291, 'streak_extended_today': False, 'user_id': 149509}
1 -> 15291149509.0
2_str -> {'display_name': '̿н̿σ̿ця̿ɪ̿α ℍ ℝ', 'has_plus': False, 'has_recent_activity_15': False, 'score': 218, 'streak_extended_today': False, 'user_id': 787165589}
2 -> 15218787165589.0
3_str -> {'display_name': 'Katarína', 'has_plus': False, 'has_recent_activity_15': False, 'score': 195, 'streak_extended_today': False, 'user_id': 1112858809}
3 -> 151951112858809.0
4_str -> {'display_name': 'super lady_megaverse', 'has_plus': False, 'has_recent_activity_15': False, 'score': 182, 'streak_extended_today': False, 'user_id': 1000899179}
4 -> 151821000899179.0
5_str -> {'display_name': 'Barush', 'has_plus': False, 'has_recent_activity_15': False, 'score': 144, 'streak_extended_today': False, 'user_id': 650968652}
5 -> 15144650968652.0
6_str -> {'display_name': 'Meggi', 'has_plus': False, 'has_recent_activity_15': False, 'score': 139, 'streak_extended_today': False, 'user_id': 903563330}
6 -> 15139903563330.0
7_str -> {'display_name': 'Violeta Rey', 'has_plus': False, 'has_recent_activity_15': False, 'score': 82, 'streak_extended_today': False, 'user_id': 1465933335}
7 -> 15821465933335.0
8_str -> {'display_name': 'Yahir', 'has_plus': False, 'has_recent_activity_15': False, 'score': 81, 'streak_extended_today': False, 'user_id': 1375133380}
8 -> 15811375133380.0
9_str -> {'display_name': 'Marie', 'has_plus': False, 'has_recent_activity_15': False, 'score': 78, 'streak_extended_today': False, 'user_id': 1173447270}
9 -> 15781173447270.0
10_str -> {'display_name': 'Alex', 'has_plus': False, 'has_recent_activity_15': False, 'score': 77, 'streak_extended_today': False, 'user_id': 756035570}
10 -> 1577756035570.0
11_str -> {'display_name': 'youba', 'has_plus': False, 'has_recent_activity_15': False, 'score': 74, 'streak_extended_today': False, 'user_id': 931477400}
11 -> 1574931477400.0
12_str -> {'display_name': 'Beatrice', 'has_plus': False, 'has_recent_activity_15': False, 'score': 70, 'streak_extended_today': False, 'user_id': 985997963}
12 -> 1570985997963.0
13_str -> {'display_name': 'Madzia', 'has_plus': False, 'has_recent_activity_15': False, 'score': 69, 'streak_extended_today': False, 'user_id': 1113521957}
13 -> 15691113521957.0
14_str -> {'display_name': 'Olaf Bolaf', 'has_plus': False, 'has_recent_activity_15': False, 'score': 65, 'streak_extended_today': False, 'user_id': 1045263708}
14 -> 15651045263708.0
15_str -> {'display_name': 'leòn', 'has_plus': False, 'has_recent_activity_15': False, 'score': 65, 'streak_extended_today': False, 'user_id': 551182683}
15 -> 1565551182683.0
16_str -> {'display_name': 'Renske', 'has_plus': False, 'has_recent_activity_15': False, 'score': 62, 'streak_extended_today': False, 'user_id': 963094331}
16 -> 1562963094331.0
17_str -> {'display_name': 'Kev', 'has_plus': False, 'has_recent_activity_15': False, 'score': 60, 'streak_extended_today': False, 'user_id': 41570738}
17 -> 156041570738.0
18_str -> {'display_name': 'Urszula Racka', 'has_plus': False, 'has_recent_activity_15': False, 'score': 60, 'streak_extended_today': False, 'user_id': 1587509021}
18 -> 15601587509021.0
19_str -> {'display_name': 'Blanka', 'has_plus': False, 'has_recent_activity_15': False, 'score': 59, 'streak_extended_today': False, 'user_id': 992795426}
19 -> 1559992795426.0
20_str -> {'display_name': 'Paty', 'has_plus': False, 'has_recent_activity_15': False, 'score': 59, 'streak_extended_today': False, 'user_id': 36362270}
20 -> 155936362270.0
21_str -> {'display_name': 'Dominika', 'has_plus': False, 'has_recent_activity_15': False, 'score': 58, 'streak_extended_today': False, 'user_id': 207117481}
21 -> 1558207117481.0
22_str -> {'display_name': 'Evka', 'has_plus': False, 'has_recent_activity_15': False, 'score': 57, 'streak_extended_today': False, 'user_id': 1169940103}
22 -> 15571169940103.0
23_str -> {'display_name': 'Salah eddine boukheit', 'has_plus': False, 'has_recent_activity_15': False, 'score': 50, 'streak_extended_today': False, 'user_id': 1575647971}
23 -> 15501575647971.0
24_str -> {'display_name': 'carlsantia', 'has_plus': False, 'has_recent_activity_15': False, 'score': 48, 'streak_extended_today': False, 'user_id': 385636580}
24 -> 1548385636580.0
25_str -> {'display_name': 'Frodo', 'has_plus': False, 'has_recent_activity_15': False, 'score': 48, 'streak_extended_today': False, 'user_id': 1529933849}
25 -> 15481529933849.0
26_str -> {'display_name': 'Sigrid', 'has_plus': False, 'has_recent_activity_15': False, 'score': 45, 'streak_extended_today': False, 'user_id': 1161303741}
26 -> 15451161303741.0
27_str -> {'display_name': 'Yasmine De Gallan', 'has_plus': False, 'has_recent_activity_15': False, 'score': 44, 'streak_extended_today': False, 'user_id': 1368950070}
27 -> 15441368950070.0
28_str -> {'display_name': 'Cyril Kluss', 'has_plus': False, 'has_recent_activity_15': False, 'score': 42, 'streak_extended_today': False, 'user_id': 1590195472}
28 -> 15421590195472.0
29_str -> {'display_name': 'Sziszkó', 'has_plus': False, 'has_recent_activity_15': False, 'score': 24, 'streak_extended_today': False, 'user_id': 1511770231}
29 -> 15241511770231.0
30_str -> {'display_name': 'Zdravka Ivanova', 'has_plus': False, 'has_recent_activity_15': False, 'score': 15, 'streak_extended_today': False, 'user_id': 1346414724}
30 -> 15151346414724.0
icon_str -> mdi:bulletin-board
", TypeError("'<' not supported between instances of 'int' and 'str'"))
```

**Comment by Makhuta** [comment]
It looks like the InfluxDB have problem serializing/unserializing the data for sensors extra attrs (in your case it looks like user leaderboards). I forced the attributes to have keys as str so the key type shouldn't be the problem now. The HACS should recognise the update some time in next 24h (or you can force it by restarting HACS), let me know if it fixed the issue.

**Comment by peteh** [comment]
Hey thanks for checking it so quickly, that fixes the error message. 

Best regards, Pete
